### ISSUE TITLE
Import auth plugins

### ISSUE THREAD

**Issue by ahmetb** [rajatjindal/kubectl-whoami#3]
Can't use this plugin currently on GCP because auth for client-go auth packages is not done.

**Comment by rajatjindal** [comment]
Hi Ahmet,

I think I did that, and released a new version for that https://github.com/rajatjindal/kubectl-whoami/releases/tag/v0.0.3 (I tested using OIDC provider and assumed that GCP auth should work in a similar fashion).

If you have tried v0.0.3 already, and it still does not work, please let me know.

Thanks
Rajat Jindal

**Comment by ahmetb** [comment]
Yes having issues with v0.0.3.

**Comment by ahmetb** [comment]
I get error:

> Error: could not identify auth tupe

**Comment by rajatjindal** [comment]
Hi Ahmet,

can you please share your auth config with me (without the secrets of-course :) ), i want to make sure i do test the config that you are using.

I've setup the google cloud account so that I can really test it with real cluster.

Thanks
Rajat Jindal

**Comment by rajatjindal** [comment]
Hi @ahmetb 

I am not very well versed with how auth providers work. I looked at the kubectl code, and it seems like the PR #4  should fix it.

can you please look at it if you get chance to see if that makes sense?

Thanks
Rajat Jindal

**Comment by rajatjindal** [comment]
fixed by #4
