### ISSUE TITLE
fix ModifySecret references

### ISSUE THREAD

**Issue by ahmetb** [rajatjindal/kubectl-whoami#5]
e.g. 	root := cmd.NewCmdModifySecret(genericclioptions.IOStreams{In: os.Stdin, Out: os.Stdout, ErrOut: os.Stderr})

I was about to refer to this as a "canonical plugin example" but it's not good like this. :)

**Comment by rajatjindal** [comment]
I dont even know how I missed notification for this issue. seeing it only today. I will address this soon.

**Comment by rajatjindal** [comment]
fixed. thanks Ahmet.
