### ISSUE TITLE
--version is "unknown"

### ISSUE THREAD

**Issue by olivierlemasle** [rajatjindal/kubectl-whoami#8]
With `kubectl-whoami` installed with Krew or downloaded from GitHub releases:

```
$ kubectl whoami --version
unknown
```

It seems that the version was passed to `go build` [when using `build.sh`](https://github.com/rajatjindal/kubectl-whoami/blob/3b8cb7c2a6bc870c049ea26735ea37ab2dea84b9/build.sh#L13), but it is not set with Goreleaser.

**Comment by rajatjindal** [comment]
good catch. do you know how to fix that? i will investigate, thanks a lot.
